### ISSUE TITLE
Seeing when starting the app Error: Failed to find .rc file at default paths

### ISSUE THREAD

**Issue by mmraghavendra** [luisalfonsopreciado/finance-visualizer#2]
I am seeing below error, am missing any

> env-cmd -e env react-scripts start

Error: Failed to find .rc file at default paths: [./.env-cmdrc,./.env-cmdrc.js,./.env-cmdrc.json]

**Comment by mmraghavendra** [comment]
Resolved above by creating .env-cmdrc file in root directory
can you share the sample data to be placed in this file

**Comment by vtbalaji** [comment]
I too face the same issue.  could you share more details on setup.   I am happy to work and enhance on this.

**Comment by luisalfonsopreciado** [comment]
Sample data can now be found in README.

**Comment by vtbalaji** [comment]
yes it's working.  thx for your quick reply.
